# ==========================================================================
# Project:   Nodelink
# Copyright: @2011 Concord Consortium
# ==========================================================================

config :nodelink, 
         :required => 'raphael_views/raphael_views',
         :load_fixtures => true,
         :css_theme => 'ace.nodelink'
